apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: f2ihr26uw-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/f2ihr26uw-dotnet-basic-gitops